// Generated by Supabase MCP from migration 0001_init.sql.
// Regenerate with `mcp__supabase__generate_typescript_types` after schema changes.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      abuse_events: {
        Row: {
          action_taken: string | null
          created_at: string
          details: Json | null
          event_type: string
          id: string
          user_id: string | null
        }
        Insert: {
          action_taken?: string | null
          created_at?: string
          details?: Json | null
          event_type: string
          id?: string
          user_id?: string | null
        }
        Update: {
          action_taken?: string | null
          created_at?: string
          details?: Json | null
          event_type?: string
          id?: string
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "abuse_events_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      countries: {
        Row: {
          flag_emoji: string | null
          id: string
          is_enabled: boolean
          iso_code: string
          name: string
        }
        Insert: {
          flag_emoji?: string | null
          id?: string
          is_enabled?: boolean
          iso_code: string
          name: string
        }
        Update: {
          flag_emoji?: string | null
          id?: string
          is_enabled?: boolean
          iso_code?: string
          name?: string
        }
        Relationships: []
      }
      crypto_payments: {
        Row: {
          amount_usd_cents: number
          confirmed_at: string | null
          created_at: string
          crypto_amount: string | null
          crypto_currency: string | null
          external_id: string
          id: string
          provider: string
          status: string
          user_id: string
          webhook_payload: Json | null
        }
        Insert: {
          amount_usd_cents: number
          confirmed_at?: string | null
          created_at?: string
          crypto_amount?: string | null
          crypto_currency?: string | null
          external_id: string
          id?: string
          provider: string
          status: string
          user_id: string
          webhook_payload?: Json | null
        }
        Update: {
          amount_usd_cents?: number
          confirmed_at?: string | null
          created_at?: string
          crypto_amount?: string | null
          crypto_currency?: string | null
          external_id?: string
          id?: string
          provider?: string
          status?: string
          user_id?: string
          webhook_payload?: Json | null
        }
        Relationships: [
          {
            foreignKeyName: "crypto_payments_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      orders: {
        Row: {
          cancelled_at: string | null
          completed_at: string | null
          country_id: string | null
          created_at: string
          expires_at: string
          id: string
          mode: string
          phone_number: string
          provider_slug: string
          retail_charged_cents: number
          service_id: string | null
          status: string
          upstream_order_id: string
          user_id: string
          wholesale_paid_cents: number
        }
        Insert: {
          cancelled_at?: string | null
          completed_at?: string | null
          country_id?: string | null
          created_at?: string
          expires_at: string
          id?: string
          mode: string
          phone_number: string
          provider_slug: string
          retail_charged_cents: number
          service_id?: string | null
          status: string
          upstream_order_id: string
          user_id: string
          wholesale_paid_cents: number
        }
        Update: {
          cancelled_at?: string | null
          completed_at?: string | null
          country_id?: string | null
          created_at?: string
          expires_at?: string
          id?: string
          mode?: string
          phone_number?: string
          provider_slug?: string
          retail_charged_cents?: number
          service_id?: string | null
          status?: string
          upstream_order_id?: string
          user_id?: string
          wholesale_paid_cents?: number
        }
        Relationships: [
          {
            foreignKeyName: "orders_country_id_fkey"
            columns: ["country_id"]
            isOneToOne: false
            referencedRelation: "countries"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "orders_service_id_fkey"
            columns: ["service_id"]
            isOneToOne: false
            referencedRelation: "services"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "orders_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      pricing_rules: {
        Row: {
          country_id: string | null
          created_at: string
          flat_fee_cents: number
          id: string
          is_active: boolean
          markup_percent: number
          min_retail_cents: number
          priority: number
          service_id: string | null
        }
        Insert: {
          country_id?: string | null
          created_at?: string
          flat_fee_cents?: number
          id?: string
          is_active?: boolean
          markup_percent?: number
          min_retail_cents?: number
          priority?: number
          service_id?: string | null
        }
        Update: {
          country_id?: string | null
          created_at?: string
          flat_fee_cents?: number
          id?: string
          is_active?: boolean
          markup_percent?: number
          min_retail_cents?: number
          priority?: number
          service_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "pricing_rules_country_id_fkey"
            columns: ["country_id"]
            isOneToOne: false
            referencedRelation: "countries"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "pricing_rules_service_id_fkey"
            columns: ["service_id"]
            isOneToOne: false
            referencedRelation: "services"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          created_at: string
          id: string
          is_admin: boolean
          is_banned: boolean
          referral_code: string | null
          referred_by: string | null
          total_spent_cents: number
          total_topped_up_cents: number
          wallet_balance_cents: number
        }
        Insert: {
          created_at?: string
          id: string
          is_admin?: boolean
          is_banned?: boolean
          referral_code?: string | null
          referred_by?: string | null
          total_spent_cents?: number
          total_topped_up_cents?: number
          wallet_balance_cents?: number
        }
        Update: {
          created_at?: string
          id?: string
          is_admin?: boolean
          is_banned?: boolean
          referral_code?: string | null
          referred_by?: string | null
          total_spent_cents?: number
          total_topped_up_cents?: number
          wallet_balance_cents?: number
        }
        Relationships: [
          {
            foreignKeyName: "profiles_referred_by_fkey"
            columns: ["referred_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      provider_services: {
        Row: {
          available_count: number | null
          country_id: string | null
          id: string
          is_enabled: boolean
          last_synced_at: string | null
          provider_slug: string
          service_id: string | null
          upstream_country_code: string
          upstream_operator: string | null
          upstream_service_code: string
          wholesale_price_cents: number | null
        }
        Insert: {
          available_count?: number | null
          country_id?: string | null
          id?: string
          is_enabled?: boolean
          last_synced_at?: string | null
          provider_slug: string
          service_id?: string | null
          upstream_country_code: string
          upstream_operator?: string | null
          upstream_service_code: string
          wholesale_price_cents?: number | null
        }
        Update: {
          available_count?: number | null
          country_id?: string | null
          id?: string
          is_enabled?: boolean
          last_synced_at?: string | null
          provider_slug?: string
          service_id?: string | null
          upstream_country_code?: string
          upstream_operator?: string | null
          upstream_service_code?: string
          wholesale_price_cents?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "provider_services_country_id_fkey"
            columns: ["country_id"]
            isOneToOne: false
            referencedRelation: "countries"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "provider_services_service_id_fkey"
            columns: ["service_id"]
            isOneToOne: false
            referencedRelation: "services"
            referencedColumns: ["id"]
          },
        ]
      }
      received_messages: {
        Row: {
          content: string
          extracted_code: string | null
          id: string
          order_id: string
          received_at: string
          sender: string | null
        }
        Insert: {
          content: string
          extracted_code?: string | null
          id?: string
          order_id: string
          received_at?: string
          sender?: string | null
        }
        Update: {
          content?: string
          extracted_code?: string | null
          id?: string
          order_id?: string
          received_at?: string
          sender?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "received_messages_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
        ]
      }
      services: {
        Row: {
          created_at: string
          display_order: number
          icon_url: string | null
          id: string
          is_enabled: boolean
          name: string
          slug: string
        }
        Insert: {
          created_at?: string
          display_order?: number
          icon_url?: string | null
          id?: string
          is_enabled?: boolean
          name: string
          slug: string
        }
        Update: {
          created_at?: string
          display_order?: number
          icon_url?: string | null
          id?: string
          is_enabled?: boolean
          name?: string
          slug?: string
        }
        Relationships: []
      }
      wallet_transactions: {
        Row: {
          amount_cents: number
          balance_after_cents: number
          created_at: string
          id: string
          note: string | null
          reference_id: string | null
          reference_type: string | null
          type: string
          user_id: string
        }
        Insert: {
          amount_cents: number
          balance_after_cents: number
          created_at?: string
          id?: string
          note?: string | null
          reference_id?: string | null
          reference_type?: string | null
          type: string
          user_id: string
        }
        Update: {
          amount_cents?: number
          balance_after_cents?: number
          created_at?: string
          id?: string
          note?: string | null
          reference_id?: string | null
          reference_type?: string | null
          type?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "wallet_transactions_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      is_admin: { Args: never; Returns: boolean }
      wallet_apply: {
        Args: {
          p_amount_cents: number
          p_note?: string
          p_reference_id?: string
          p_reference_type?: string
          p_type: string
          p_user_id: string
        }
        Returns: {
          amount_cents: number
          balance_after_cents: number
          created_at: string
          id: string
          note: string | null
          reference_id: string | null
          reference_type: string | null
          type: string
          user_id: string
        }
        SetofOptions: {
          from: "*"
          to: "wallet_transactions"
          isOneToOne: true
          isSetofReturn: false
        }
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
